let firstInput = prompt("enter first number")
let secondInput = prompt("enter second number")
let checkFirst = parseInt(firstInput)
let checkSecond = parseInt(secondInput)
if(isNaN(checkFirst) || isNaN(checkSecond)) alert("Invalid input, please enter number")
else alert(+firstInput + +secondInput)

// let result = Number(number1) + Number(number2)
// if(isNaN(result))alert("Invalid Number")
// else alert(result)